In [54]:
import numpy as np

with open('input') as f:
    data = f.read()
    
data = '''.#.
..#
###'''

In [57]:
data = data.replace(".", "0").replace("#", "1")
start = np.array([np.array(list(line)) for line in data.splitlines()], dtype=int)

In [75]:
padding = (30, 30, 6)

prior = np.zeros(padding)
prior[17:20, 17:20, 3] = start
posterior = None

for n in range(6):
    
    posterior = prior.copy()
    print(prior[17:20, 17:20, 2])
    for x, x_val in enumerate(prior):
        for y, y_val in enumerate(x_val):
            for z, value in enumerate(y_val):
                
                if (x > 0 and y > 0 and z > 0 and 
                    x < padding[0] - 1 and y < padding[1] - 1 and z < padding[2] - 1):
                    
                    # Get neighbours
                    neighbours = np.array([
                        prior[x + 1, y, z],
                        prior[x - 1, y, z],
                        prior[x, y + 1, z],
                        prior[x, y - 1, z],
                        prior[x, y, z + 1],
                        prior[x, y, z - 1]
                    ])
                    
                    if value == 1 and sum(neighbours) not in [2,3]:
                        posterior[x, y, z] = 0
                    elif value == 0 and sum(neighbours) == 3:
                        posterior[x, y, z] = 1
                        
    prior = posterior.copy()
    

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [74]:
posterior[17:20, 17:20, 2]

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [17]:
prior

array([[[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       ...,

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0.